{{- if .Values.ocpSecretsStoreCsiVault.secretProviderClass.enabled }}
{{- $hashicorp_vault_found := false }}
{{- range .Values.clusterGroup.applications }}
  {{- if . }}
    {{- if eq .chart "hashicorp-vault" }}
      {{- $hashicorp_vault_found = true }}
    {{- end }}
  {{- end }}
{{- end }}
{{- $isHubStyleAuth := or (eq (include "openshift_sscsi_vault.ishubcluster" .) "true") $hashicorp_vault_found }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.ocpSecretsStoreCsiVault.secretProviderClass.name }}
  namespace: {{ .Values.ocpSecretsStoreCsiVault.rbac.serviceAccount.namespace }}
spec:
  provider: vault
{{- with .Values.ocpSecretsStoreCsiVault.secretObjects }}
  secretObjects:
{{- toYaml . | nindent 4 }}
{{- end }}
  parameters:
    vaultAddress: "https://vault-vault.{{ .Values.global.hubClusterDomain }}"
    vaultSkipTLSVerify: {{ .Values.ocpSecretsStoreCsiVault.tls.vaultSkipTLSVerify | quote }}
{{- if .Values.ocpSecretsStoreCsiVault.tls.vaultCACertPath }}
    vaultCACertPath: {{ .Values.ocpSecretsStoreCsiVault.tls.vaultCACertPath | quote }}
{{- end }}
{{- if .Values.ocpSecretsStoreCsiVault.tls.vaultTLSServerName }}
    vaultTLSServerName: {{ .Values.ocpSecretsStoreCsiVault.tls.vaultTLSServerName | quote }}
{{- end }}
{{- if $isHubStyleAuth }}
    vaultKubernetesMountPath: {{ .Values.ocpSecretsStoreCsiVault.vault.hubMountPath | quote }}
    roleName: {{ .Values.ocpSecretsStoreCsiVault.rbac.rolename | quote }}
{{- else }}
    vaultKubernetesMountPath: {{ $.Values.global.clusterDomain | quote }}
    roleName: {{ printf "%s-role" $.Values.global.clusterDomain | quote }}
{{- end }}
    objects: |
{{- range .Values.ocpSecretsStoreCsiVault.objects }}
      - objectName: {{ .objectName | quote }}
        secretPath: {{ .secretPath | quote }}
        secretKey: {{ .secretKey | quote }}
{{- end }}
{{- end }}
